spring:
  application:
    name: rest-kafka

  kafka:
    producer:
      bootstrap-servers: '127.0.0.1:9092'
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080